export class Proveedores{
constructor (
  public  ID: number,
  public DETALLE_DIRECCION: string,
  public  NOMBRE: string,
  public  ALIAS: string,
  public CONTACTO:string,
  public CARGO: string,
  public  DIRECCION: string,
  public  E_MAIL: string,
  public FECHA_INGRESO:string,
  public FECHA_ULT_MOV:Date,
  public TELEFONO1: string,
  public TELEFONO2:string ,
  public FAX: string ,
  public  ORDEN_MINIMA: number,
  public DESCUENTO: number,
  public TASA_INTERES_MORA: number,
  public LOCAL:string,
  public CONGELADO: string,
  public CONTRIBUYENTE: string,
  public CONDICION_PAGO: number,
  public MONEDA: string,
  public PAIS:string,
  public CATEGORIA_PROVEED: string,
  public MULTIMONEDA: string,
  public SALDO: number,
  public  SALDO_LOCAL:  number,
  public SALDO_DOLAR:  number,
  public NOTAS:string,
  public  RUBRO1_PROV: number,
  public RUBRO2_PROV: string,
  public  RUBRO3_PROV: string,
  public RUBRO4_PROV: string,
  public  RUBRO5_PROV: string,
  public RUBRO1_PROVEEDOR: string,
  public RUBRO2_PROVEEDOR:string,
  public RUBRO3_PROVEEDOR: string,
  public RUBRO4_PROVEEDOR: string,
  public  RUBRO5_PROVEEDOR:string,
  public  GLN: string,
  public UBICACION:number,
  public ACTIVO:string,
  public TIPO_CONTRIBUYENTE:string,
  public RUBRO6_PROVEEDOR: string,
  public RUBRO7_PROVEEDOR: string,
  public RUBRO8_PROVEEDOR: string,
  public  RUBRO9_PROVEEDOR: string,
  public  RUBRO10_PROVEEDOR: string,
  public MODELO_RETENCION: string,
  public CODIGO_IMPUESTO: number,
  public  DIVISION_GEOGRAFICA1: string,
  public DIVISION_GEOGRAFICA2: string,
  public AUTORETENEDOR:string,
  public  REGIMEN_TRIB: string,
  public  SALDO_TRANS:number,
  public  SALDO_TRANS_LOCAL: number,
  public  SALDO_TRANS_DOLAR:number,
  public  PERMITE_DOC_GP: string,
  public  PARTICIPA_FLUJOCAJA:  string,
  public  CURP:  string,
  public USUARIO_CREACION: string,
  public  FECHA_HORA_CREACION: null,
  public   USUARIO_ULT_MOD:  string,
  public  FCH_HORA_ULT_MOD: Date,
  public  IMPUESTO1_INCLUIDO: string,
  public XSLT_PERSONALIZADO:  string,
  public UBICACIONDOCELECTRONICO:  string,
  public EMAIL_DOC_ELECTRONICO:  string,
  public  EMAIL_DOC_ELECTRONICO_COPIA:  string,
  public  ACEPTA_DOC_ELECTRONICO: string,
  public  INTERNACIONES:  string,
  public TIPO_IMPUESTO:number,
  public  TIPO_TARIFA: number,
  public PORC_TARIFA: number,
  public TIPIFICACION_PROVEEDOR: number,
  public  DIVISION_GEOGRAFICA3: string,
  public  DIVISION_GEOGRAFICA4: string,
  public  ITEM_HACIENDA_COMPRA: string,
  public  TIPO_CF: string,
  public  USA_PLAME: string,
  public IMP_CATEGORIA: string,
  public  SISTEMA_PENSIONES: string,
  public  IMP_NACIONAL: number,
  public  IMP_PRIVADO:number,
  public  DOMICILIADO: string,
  public  CONVENIO: string,
  public  NUM_IDENT_NO_DOMIC: string,
  public  NUM_IDENT_FISC_BENEF: string,
  public  TIPO_VINCULACION: string,
  public  TASA_RETENCION: string,
  public EXONERACION_OPER: string,
  public BUEN_CONTRIBUYENTE: string,
  public AGENTE_RETENCION:string,
  public  IMPUESTO_RENTA: number,
  public  RENTA_ASUMIDA: string,
  public   ULT_NUM_ENVIO: string,
  public   NUM_RES_COACTIVA: string,
  public  GRANDES_COMPRA_SEMT:string,
  public TIPO_SERVICIO: string,
  public PDB_EXPORTADORES: string,

){}

}