export const environment = {
  production: false,
  maxCharCodigoProd: 6,
  preURL:'http://api_irp',
  preURL2:'http://api_isa',
  TestURL:'_test',
  postURL:'.di-apps.co.cr/api/',
  prdMode:false,
  proveedoresURL:'Proveedores/',
  articulosURL:'ONE_ArtProv/',
  idProvedorParam:'?IDProv=',
  bodegasURL:'ONE_Bodega',
  ultimaOrdenCompraURL:'ONE_Consec',
  consultarOrdenCompraLineasURLSoftland:'ONE_OCLinQuery/?oc=',
  consultarOrdenCompraLineasURL:'ONE_OCLin/?oc=',
  usuarioParam: '&Usuario=',
  usuarioAuthParam: '?Usuario=',
  claveParam: '?Clave=',
  usuariosURL:    'ONE_Aut/',
  ordenCompraURL:'ONE_OC',
  idParam :'?ID=',
  numParam: '&Num=',
  ordenCompraEstadoURL:'ONE_OCQuery/?estado=',
  lineasPostURL:'ONE_OCLin',
  ONE_UserAprob:'ONE_UserAprob',
  ONE_OCAprob:'ONE_OCAprob',
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  emailApi:'Email/',
  ONE_ListUserAprob:'ONE_ListUserAprob',
  gestorArchivos:'cargar-archivo',
  tipoParam:'?tipo=',
  tipoParam2:'&Tipo=',
  nombreParam:'&Nombre=',
  ONE_GestorArch:'ONE_GestorArch'
};
