export const environment = {
  production: true,
  maxCharCodigoProd: 6,
  preURL:'http://api_irp',
  TestURL:'_test',
  postURL:'.di-apps.co.cr/api/',
  prdMode:false,
  proveedoresURL:'Proveedores/',
  articulosURL:'ONE_ArtProv/',
  idProvedorParam:'?IDProv=',
  bodegasURL:'ONE_Bodega',
  ultimaOrdenCompraURL:'ONE_Consec',
  consultarOrdenCompraLineasURLSoftland:'ONE_OCLinQuery/?oc=',
  consultarOrdenCompraLineasURL:'ONE_OCLin/?oc=',
  usuariosURL:    'ONE_Users/',
  ordenCompraURL:'ONE_OC',
  idParam :'?ID=',
  usuarioParam: '&Usuario= ',
  numParam: '&Num= ',
  ordenCompraEstadoURL:'ONE_OCQuery/?estado=',
  lineasPostURL:'ONE_OCLin',
  ONE_UserAprob:'ONE_UserAprob',
  ONE_OCAprob:'ONE_OCAprob',
  mapboxKey:'pk.eyJ1IjoibWhlcnJhIiwiYSI6ImNrcWxhdXk4eTByMDUyd28xNnZ2b2hoMjMifQ.IrIAxPGO4oFiRVR8U5sqkA',
  
};
